services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    container_name: ollama
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama
    networks:
      - jupi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `all` for all GPUs
              capabilities: [gpu]

  backend:
    image: backend:latest
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_PATH=http://ollama:11434
    networks:
      - jupi
    working_dir: /app
    volumes:
      - "./api:/app"
    command: "uvicorn src.main:app --reload --loop asyncio --host 0.0.0.0 --port 8000"

  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - 8080:8080
    networks:
      - jupi
    working_dir: /app
    command: "http-server dist"
    depends_on:
      - backend

networks:
  jupi:
    driver: bridge
